spring:
  application:
    name: SmartCommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/zhsm?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
  jackson:
    date-format: yyyy-MM-dd hh:mm
    time-zone: GMT+8
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    group:
      dev:
        - security
        - dev
        - local
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
springfox:
  documentation:
    swagger-ui:
      enabled: true
zhsm:
  email:
    host: smtp.qq.com
    protocol: smtp
    username: 2621869236@qq.com
    pass: ptnzfqgkyhwmdhgb
  jwt:
    token-header: Authorization
    secret: awkdlawmdlkmawoa
    expire-time: 60 # 60分钟
    token-head: Base
logging:
  level:
    top.ctong.commerce.smartcommerce: debug